USE BancaVirtual2
go 
CREATE OR ALTER PROCEDURE [BancaVirtual].[sp_crm_notif_sms_cr_encuesta_satisfaccion_crbv]
@AI_ID INT OUTPUT,
@AI_SOLICITUD INT,
@AS_USUARIO VARCHAR(15),
@AS_MSJ VARCHAR(100) OUTPUT
AS
DECLARE @LI_ID INT,
	@LI_ID_CLIENTE INT,
	@LS_DATOS VARCHAR(255),
	@LI_TIPO_NOTIFICACION INT,
	@LI_RET INT,
	@LDT_FECHA_SOLICITUD DATETIME,
	@LS_MENSAJE  VARCHAR(500),
	@LS_CREDITO VARCHAR(50),
	@LS_CREDITO_REF VARCHAR(50),
	@LS_LINK_ENCUESTA_SATISFACCION VARCHAR(400)


	SET @LDT_FECHA_SOLICITUD  = PARAMETROS.dbo.FechaSistema()

	SELECT  @LS_DATOS = map_credito,
			@LS_CREDITO = map_credito
	FROM CREDITO..SL_MEDIO_APROB 
	WHERE 
			map_solicitud = @AI_SOLICITUD

	SELECT @LI_ID_CLIENTE = sol_cliente FROM CREDITO..SL_SOLICITUD where sol_solicitud = @AI_SOLICITUD
	and sol_estado = 'D'

SET @LS_CREDITO_REF = @LS_CREDITO

SET @LS_CREDITO = REPLICATE('X', LEN(@LS_CREDITO)/2 + 1) + SUBSTRING (@LS_CREDITO, (len (@LS_CREDITO) / 2 )+ 1, len (@LS_CREDITO))

	--Ingresar parametro de co parametros para la encuesta de satisfacción 
	SET @LS_LINK_ENCUESTA_SATISFACCION = 'https:googledrive/encuestaDifare'


SELECT 
	@LI_TIPO_NOTIFICACION = tns_tipo_notificacion,
	@LS_MENSAJE =  tns_mensaje
FROM CLIENTES..CRM_SERVICIOS_NOTIFICACION_SMS  
WHERE tns_codigo = 'CR_DES_WEB'

EXEC @LI_RET = master..xp_sprintf @LS_DATOS OUT, @LS_MENSAJE, @LS_CREDITO, @LS_LINK_ENCUESTA_SATISFACCION
				
IF @LI_RET = 1 OR @@ERROR<>0
BEGIN
	ROLLBACK TRANSACTION TR_NOT
	SET @AS_MSJ = 'ERROR EN EL MENSAJE'
	RETURN -1
END

IF NOT EXISTS (SELECT 1
		FROM CLIENTES..CRM_SERVICIOS_NOTIFICACION_SMS  
		WHERE tns_tipo_notificacion = @LI_TIPO_NOTIFICACION 
		AND tns_estado = 'A' )
BEGIN
	SET @AS_MSJ = 'NO EXISTE SERVICIO'
	RETURN 1
END



EXEC @LI_RET = CLIENTES.dbo.sp_crm_notificaciones_sms_insertar
	@AI_ID = @LI_ID  OUTPUT,
	@ADT_FECHA_SOLICITUD = @LDT_FECHA_SOLICITUD,
	@AI_ID_CLIENTE = @LI_ID_CLIENTE ,
	@AS_REFERENCIA = @LS_CREDITO_REF,
	@AS_DATOS = @LS_DATOS,
	@AI_TIPO_NOTIFICACION = @LI_TIPO_NOTIFICACION,
	@AS_USUARIO = 'ADMIN' ,
	@AS_MSJ = @AS_MSJ OUTPUT



RETURN @LI_RET


