USE CREDITO
GO

/*FECHA		AUTOR	DESCRIPCION
==========	=====	==========================================================
2007-01-01	BMR	CREACION
2010-07-29	BMR	SE ELIMINA EL CAMPO QUE INDICA SI EL DOCUMENTO ESTA IMPRESO
2011-05-30	BME	SE INCLUYEN LOS CAMPOS ENTIDAD FINANCIERA, TIPO DE CUENTA Y NUMERO DE CUENTA
*/

CREATE   OR ALTER   PROCEDURE [dbo].[sp_cr_desembolso_insertar]
	@AL_SOLICITUD INT,
	@AS_USUARIO VARCHAR(15),
	@AS_TIPO_DESEMBOLSO CHAR(3),
	@AS_REFERENCIA VARCHAR(20),
	@AS_FONDO VARCHAR(3),
	@AS_SUBFONDO VARCHAR(3),
	@ADT_FECHA_DESC DATETIME,
	@AI_ENTIDAD_FINANCIERA INTEGER,
	@AS_TIPO_CUENTA CHAR(1),
	@AS_NUMERO_CUENTA VARCHAR(20),
	@AS_CREDITO VARCHAR(20) OUT,
	@AM_VALOR_PAGAR MONEY OUT,
	@AS_MSJ VARCHAR(100) OUT,
	@ADT_FECHA_OTORGAMIENTO DATETIME = NULL,
	@AM_MONTO MONEY = NULL
AS
BEGIN
	DECLARE @LI_SEC INTEGER,
			@LB_DESEMBOLSO_PARCIAL BIT

	IF EXISTS (SELECT 1 FROM CR_CREDITO, SL_MEDIO_APROB 
				WHERE map_solicitud = @AL_SOLICITUD 
				AND map_credito = cre_credito )	
	BEGIN
		SET @AS_MSJ = 'SOLICITUD YA DESEMBOLSADA Y GENERADA COMO CARTERA'
		RETURN -1
	END

	SELECT @LB_DESEMBOLSO_PARCIAL = sol_desembolso_parcial
	FROM SL_SOLICITUD 
	WHERE sol_solicitud = @AL_SOLICITUD

	-- SI LA SOLICITUD NO CORRESPONDE A DESEMBOLSO PARCIAL
	IF @LB_DESEMBOLSO_PARCIAL = 0
	BEGIN	
		IF EXISTS (SELECT 1 FROM CR_DESEMBOLSO WHERE des_solicitud = @AL_SOLICITUD )	
		BEGIN
			SET @AS_MSJ = 'SOLICITUD YA DESEMBOLSADA'
			RETURN -1
		END
	END

	/*
	IF EXISTS (SELECT * FROM CR_DESEMBOLSO WHERE des_solicitud = @AL_SOLICITUD )	
	BEGIN
		SET @AS_MSJ = 'SOLICITUD YA DESEMBOLSADA'
		RETURN -1
	END
	*/

	DECLARE @LS_OFICINA CHAR(4),
		@LDT_FECHA DATETIME,
		@LM_MONTO MONEY,
		@LM_VALOR_DESC_TRANS_AHORRO_NC MONEY

	EXEC sp_FechaHoraSistema @LDT_FECHA OUTPUT

	SELECT 	@LS_OFICINA = sol_oficina
	FROM SL_SOLICITUD, CR_PRODUCTOS
	WHERE sol_solicitud = @AL_SOLICITUD 
	AND sol_producto = pro_producto


	IF @LB_DESEMBOLSO_PARCIAL = 0
	BEGIN
		SELECT @LM_MONTO = map_monto,
			@AS_CREDITO = map_credito
		 FROM SL_MEDIO_APROB
		WHERE map_solicitud = @AL_SOLICITUD 
	END
	ELSE
	BEGIN
		SET @LM_MONTO = @AM_MONTO 
		SELECT	@AS_CREDITO = map_credito
		 FROM SL_MEDIO_APROB
		WHERE map_solicitud = @AL_SOLICITUD 
	END
	
	SELECT @AM_VALOR_PAGAR = ISNULL( SUM(des_valor), 0) 
	 FROM SL_DESCUENTOS
	WHERE des_solicitud = @AL_SOLICITUD
	AND des_generar_transaccion_ahorros = 0
	AND des_incluye = 1


	SELECT @LM_VALOR_DESC_TRANS_AHORRO_NC = ISNULL( SUM(des_valor), 0)
	FROM SL_DESCUENTOS, CUENTAS..AH_TIPO_TRANSACCION
	WHERE des_solicitud = @AL_SOLICITUD
	AND des_generar_transaccion_ahorros = 1
	AND des_tipo_trans = ttr_tipo_trans
	AND ttr_signo = 1
	AND des_incluye = 1


	

	DECLARE @LD_FECHA DATETIME
	SET @LD_FECHA = dbo.FechaSistema()

	IF NOT EXISTS ( SELECT 1 FROM CR_TIPO_DESEMBOLSO
					WHERE tds_tipo_desembolso = @AS_TIPO_DESEMBOLSO
					AND tds_estado = 'A' )
	BEGIN
		SET @AS_MSJ = 'NO EXISTE TIPO DE DESEMBOLSO ('+ISNULL (@AS_TIPO_DESEMBOLSO, '') + ')'
		RETURN -1
	END

	IF @ADT_FECHA_OTORGAMIENTO IS NULL
		SET @ADT_FECHA_OTORGAMIENTO = @ADT_FECHA_DESC
		
	SELECT @LI_SEC = max(des_sec) from CR_DESEMBOLSO where des_solicitud = @AL_SOLICITUD

	SELECT @LI_SEC = ISNULL(@LI_SEC,0)

	SET @LI_SEC = @LI_SEC + 1 
	
	IF @LB_DESEMBOLSO_PARCIAL = 0 
		SET @AM_VALOR_PAGAR = @LM_MONTO - @AM_VALOR_PAGAR - @LM_VALOR_DESC_TRANS_AHORRO_NC
	ELSE
	BEGIN	
		/* SOLAMENTE EN EL PRIMER REGISTRO DE DESEMBOLSO DISMINUYE TODOS LOS VALORES*/
		/* EN LOS SIGUIENTES REGISTROS SE DEBE DESEMBOLSAR EL MONTO*/
		
		IF 	@LI_SEC = 1
			SET @AM_VALOR_PAGAR = @LM_MONTO - @AM_VALOR_PAGAR - @LM_VALOR_DESC_TRANS_AHORRO_NC 
		ELSE 
			SET @AM_VALOR_PAGAR = @LM_MONTO 	
	END	

	INSERT INTO CR_DESEMBOLSO (des_solicitud, des_sec, des_credito, des_monto, des_monto_liquidar, des_fecha, des_usuario, des_oficina, des_tipo_desembolso, des_referencia, des_pagado, 
	des_fondo, des_subfondo, des_entidad_financiera,des_tipo_cuenta,des_numero_cuenta, des_fecha_otorgamiento, des_desembolso_parcial)
	VALUES ( @AL_SOLICITUD ,
		@LI_SEC,
		@AS_CREDITO,
		@LM_MONTO,
		@AM_VALOR_PAGAR,
		@ADT_FECHA_DESC,
		@AS_USUARIO,
		@LS_OFICINA,
		@AS_TIPO_DESEMBOLSO,
		@AS_REFERENCIA,
		0,
		@AS_FONDO,
		@AS_SUBFONDO,
		@AI_ENTIDAD_FINANCIERA,
		@AS_TIPO_CUENTA,
		@AS_NUMERO_CUENTA,
		@ADT_FECHA_OTORGAMIENTO,
		0)

	DECLARE @LS_ESTADO CHAR(1)


	SELECT @LS_ESTADO = est_estado FROM SL_ESTADO WHERE est_es_desembolsado = 1


	EXEC sp_sl_solicitud_cambiar_estado @AL_SOLICITUD, @LS_ESTADO, '1', @AS_USUARIO 


	RETURN 1
END


