USE CREDITO 
GO 
/*
FECHA		AUTOR	DESCRIPCION
==========	=======	======================================================
2006-01-17	MSG		PROCESA RENOVACIONES
2007-05-02	BMR		INTERFACE CON CONTABILIDAD PARA GENERAR
					CUENTAS POR PAGAR CUANDO ES EN CHEQUE
2007-0-02	BMR		VALIDAR NUMERO DE CREDITOS VIGENTES EN PROCESO DE DESEMBOLSO
2009-01-27	DCH		ACTUALIZAR FECHA DE OTORGAMIENTO DE LA SOLICITUD
2010-03-11	DCH		TIPO DE DESEMBOLSO PARA RETANQUEO MONTO RECIBIR = 0
2010-06-07	GNF		DESEMBOLSO A CUENTA VIRTUAL (AH)
2010-07-07	BMR		ACTUALIZAR MONTO A LIQUIDAR 
2010-08-02	BMR		SE GENERA UNA TRANSACCION PARA CANCELAR RUBROS DE DESCUENTO
					FINANCIADOS QUE SE ENCUENTRAN EN CUOTA CERO
2010-08-10	BMR		LA TRANSACCION PARA SEGUROS SE GENERA COMO RECUPERACION DE SEGUROS
2010-05-30	BMR		SE GUARDA INFORMACION DE ENTIDAD FINANCIERA, TIPO DE CUENTA Y 
					NUMERO DE CUENTA  CUANDO EL TIPO DE DESEMBOLSO ES ORDEN DE PAGO
					TAMBIEN SE ACTUALIZA EL ARGUMENTO @AS_TIPO_DESEMBOLSO CHAR(2) A CHAR(3)					 
*/


CREATE  OR ALTER PROCEDURE [dbo].[sp_cr_procesar_desembolso]
@AS_USUARIO VARCHAR(15),
@AS_OFICINA CHAR(4),
@AI_SOLICITUD INT,
@AS_TIPO_DESEMBOLSO CHAR(3),
@AS_REFERENCIA VARCHAR(20),
@AS_FONDO CHAR(3),
@AS_SUBFONDO CHAR(3) = NULL,
@ADT_FECHA_DES DATETIME,
@ADT_FECHA_1ER_PG DATETIME ,
@ADEC_TASA DECIMAL ( 18, 4 ),
@AB_RENOVACION BIT = 0,
@AM_VALOR_PAGAR MONEY = 0,
@AI_ENTIDAD_FINANCIERA INTEGER = NULL,
@AS_TIPO_CUENTA CHAR(1)= NULL,
@AS_NUMERO_CUENTA VARCHAR(20) = NULL,
@AS_CREDITO VARCHAR(20) = NULL OUTPUT,
@AS_MSJ VARCHAR(100) OUTPUT,
@AS_XML_DESEMBOLSO VARCHAR(8000) = NULL
AS
BEGIN

DECLARE @LI_RET INT, 
	@LM_VALOR_PAGAR MONEY, 
	@LM_VALOR MONEY, 
	@LS_TIPO_TRANS CHAR(3), 
	@LI_TRA_ID INT,
	@LS_PRODUCTO VARCHAR (5),
	@LI_NRO_CP INTEGER,
	@AI_TIPO INTEGER,
	@LS_REFERENCIA VARCHAR(20),
	@LS_DOCUMENTO VARCHAR(20),
	@LS_TIPO_TRAN VARCHAR(3),
	@LS_MONEDA CHAR(1),
	@LM_SALDO_CUOTA_CERO MONEY,
	@LM_EFECTIVO MONEY,
	@LM_CHEQUE MONEY,
	@LI_TRAN INTEGER,
	@LS_TIPO_OPERACION CHAR(1),
	@LB_PERMITE_AUMENTO_CAPITAL BIT, 
	@LI_ES_GRUPAL BIT,
	@LI_CR_X_INTEGRANTE BIT ,
	@LS_SUBFONDO VARCHAR(3),
	@LD_TASA_MORA DECIMAL(8,2), 
	@LB_ES_AHORROS_CASH BIT,
	@LB_ES_AHORROS BIT,
	@LI_CLIENTE INT,
	@LB_DESEMBOLSO_PARCIAL BIT,
	@LB_FECHA_POST_DESEM BIT,
	@LB_CUALQ_FECHA_OTOR_CCA BIT,
	@LDT_FECHA_OTORGAMIENTO DATETIME, 
	@LB_PRECAN_CAP_DES BIT, 
	@LB_CASH_COLATERAL BIT,
	@LB_CREA_CUETA_AH_CR BIT,
	@LS_CUETA_AH_CR VARCHAR(20),
	@LS_CUENTA VARCHAR(20), 
	@LS_NOMBRE VARCHAR(30)
	
	DECLARE @TIPO_DESEMBOLSO TABLE
	(

	secuencial integer identity,
	sec integer, 
	tipo_desemb varchar(3),
	valor money
	)


	DECLARE	@LT_DESEMBOLSO TABLE (sec int, tipo_desembolso char(3), fecha_otorgamiento datetime, monto money, referencia varchar(20), entidad_financiera int, tipo_cuenta char(1),numero_cuenta varchar(20)) 




SELECT @LS_PRODUCTO = sol_producto,
@LS_MONEDA = sol_moneda,
@LS_TIPO_OPERACION = sol_tipo_operacion,
@LI_ES_GRUPAL = sol_por_grupo,
@LI_CR_X_INTEGRANTE = dbo.f_cr_obtener_parametro_b(sol_producto,'BIT_CREDITO_INTEGRAN'), 
@LB_PERMITE_AUMENTO_CAPITAL = top_permite_aumento_capital,
@LB_FECHA_POST_DESEM = dbo.f_cr_obtener_parametro_b(sol_producto,'BIT_FECHA_POST_DESEM'),
@LB_CUALQ_FECHA_OTOR_CCA = dbo.f_cr_obtener_parametro_b(sol_producto,'CCA_CUALQ_FECH_OTOR'), --PARA QUE NO VALIDE FECHA OTORGAMIENTO POR COMPRA DE CARTERA
@LI_CLIENTE = sol_cliente,
@LB_DESEMBOLSO_PARCIAL = sol_desembolso_parcial,
@LDT_FECHA_OTORGAMIENTO = sol_fecha_otorgamiento,
@LB_PRECAN_CAP_DES = dbo.f_cr_obtener_parametro_b(sol_producto,'PRECAN_CAP_DES_CASH'),
@LB_CASH_COLATERAL =  dbo.f_cr_obtener_parametro_b(sol_producto,'ES_CASH_COLATERAL'),
@LB_CREA_CUETA_AH_CR = dbo.f_cr_obtener_parametro_b(sol_producto,'BIT_CTA_RECUP_AH_CR')
FROM SL_SOLICITUD,CR_TIPO_OPERACION
WHERE sol_solicitud = @AI_SOLICITUD
AND sol_tipo_operacion = top_tipo_operacion 

SET @LB_CUALQ_FECHA_OTOR_CCA = ISNULL(@LB_CUALQ_FECHA_OTOR_CCA,0)


IF @LB_DESEMBOLSO_PARCIAL = 1 
BEGIN
	INSERT INTO @LT_DESEMBOLSO 
	(sec,tipo_desembolso,fecha_otorgamiento, monto, referencia , entidad_financiera , tipo_cuenta ,numero_cuenta )
	EXEC dbo.sp_cr_listar_desembolso_detalle
	@AI_SOLICITUD = @AI_SOLICITUD ,
	@AS_XML_DESEMBOLSO = @AS_XML_DESEMBOLSO 
	
	IF NOT EXISTS (SELECT 1 FROM @LT_DESEMBOLSO WHERE sec = 1  )
	BEGIN
		SET @AS_MSJ  = 'NO SE HA DETERMINADO LOS DESEMBOLSOS PARCIALES'
		RETURN -1
	END
	
	SELECT @AS_TIPO_DESEMBOLSO = tipo_desembolso,
	@AM_VALOR_PAGAR = monto,
	@AS_REFERENCIA  = referencia,
	@AI_ENTIDAD_FINANCIERA = entidad_financiera,
	@AS_TIPO_CUENTA =  tipo_cuenta,
	@AS_NUMERO_CUENTA = numero_cuenta
	FROM @LT_DESEMBOLSO 
	WHERE sec = 1
	AND fecha_otorgamiento = @ADT_FECHA_DES

END

	IF NOT EXISTS (SELECT * FROM CR_TIPO_DESEMBOLSO WHERE tds_tipo_desembolso = @AS_TIPO_DESEMBOLSO AND tds_estado = 'A')
	BEGIN
		SET @AS_MSJ  = 'EL TIPO DE DESEMBOLSO NO EXISTE O NO ESTA ACTIVO'
		RETURN -1
	END


SELECT @LB_ES_AHORROS_CASH = tds_es_ahorros_cash,
@LB_ES_AHORROS = tds_es_ahorros
FROM CR_TIPO_DESEMBOLSO
WHERE tds_tipo_desembolso = @AS_TIPO_DESEMBOLSO 


IF (@LS_SUBFONDO IS NULL)
BEGIN
	SELECT @LS_SUBFONDO = sol_subfondo FROM SL_SOLICITUD
	WHERE sol_solicitud = @AI_SOLICITUD
END

IF @LB_FECHA_POST_DESEM = 1 AND @LB_CUALQ_FECHA_OTOR_CCA = 0 --PARA QUE NO VALIDE FECHA OTORGAMIENTO POR COMPRA DE CARTERA
BEGIN
	
	IF @ADT_FECHA_DES < dbo.FechaSistema()
	BEGIN
		SET @AS_MSJ  = 'FECHA DE DESEMBOLSO DEBE SER MAYOR O IGUAL A LA FECHA DEL SISTEMA'
		RETURN -1
	END
END 
ELSE 
BEGIN
	
	IF @ADT_FECHA_DES <> dbo.FechaSistema() AND @LB_CUALQ_FECHA_OTOR_CCA = 0 --PARA QUE NO VALIDE FECHA OTORGAMIENTO POR COMPRA DE CARTERA
	BEGIN
		SET @AS_MSJ  = 'FECHA DE DESEMBOLSO DEBE SER IGUAL A LA FECHA DEL SISTEMA'
		RETURN -1
	END
	
	IF dbo.FechaSistema() <> @LDT_FECHA_OTORGAMIENTO AND @LB_CUALQ_FECHA_OTOR_CCA = 0 --PARA QUE NO VALIDE FECHA OTORGAMIENTO POR COMPRA DE CARTERA
	BEGIN
		SET @AS_MSJ  = 'FECHA DE OTORGAMIENTO DE LA SOLICITUD DEBE SER IGUAL A LA FECHA DEL SISTEMA'
		RETURN -1
	END
	
	IF @ADT_FECHA_DES <> @LDT_FECHA_OTORGAMIENTO
	BEGIN
		SET @AS_MSJ  = 'FECHA DE OTORGAMIENTO DE LA SOLICITUD DEBE SER IGUAL A LA FECHA DEL SISTEMA (1)'
		RETURN -1
	END
	
END 


IF ( SELECT pro_permite_f1er_pg 
		FROM CR_PRODUCTOS 
		WHERE pro_producto = @LS_PRODUCTO ) = 1
BEGIN	
	IF @ADT_FECHA_DES > @ADT_FECHA_1ER_PG
	BEGIN
		SET @AS_MSJ  = 'FECHA DE PRIMER PAGO DEBE SER MAYOR AL OTORGAMIENTO'
		RETURN -1
	END

	IF ( SELECT pro_dmin_f1er_pg 
			FROM CR_PRODUCTOS 
			WHERE pro_producto = @LS_PRODUCTO ) > DATEDIFF ( dd, @ADT_FECHA_DES , @ADT_FECHA_1ER_PG )  
	BEGIN
		SET @AS_MSJ  = 'FECHA DE PRIMER PAGO NO VALIDA (MUY CERCANA A LA FECHA DE OTORGAMIENTO)'
		RETURN -1
	END

	IF ( SELECT pro_dmax_f1er_pg 
			FROM CR_PRODUCTOS 
			WHERE pro_producto = @LS_PRODUCTO ) < DATEDIFF ( dd, @ADT_FECHA_DES , @ADT_FECHA_1ER_PG )  
	BEGIN
		SET @AS_MSJ  = 'FECHA DE PRIMER PAGO NO VALIDA (MUY LEJANA A LA FECHA DE OTORGAMIENTO)'
		RETURN -1
	END
END

-- VALIDAD DATOS DE ENTIDAD FINANCIERA PARA ORDEN DE PAGO EN EFECTIVO 
IF @AS_TIPO_DESEMBOLSO = 'OPE' AND @AI_ENTIDAD_FINANCIERA IS NULL
BEGIN
		SET @AS_MSJ  = 'PARA ORDEN DE PAGO EN EFECTIVO DEBE INGRESAR LA ENTIDAD FINANCIERA'
		RETURN -1
END

-- VALIDAD DATOS DE ENTIDAD FINANCIERA PARA ORDEN DE PAGO EN CHEQUE
IF @AS_TIPO_DESEMBOLSO = 'OPC'
BEGIN
	IF @AI_ENTIDAD_FINANCIERA IS NULL
	BEGIN
		SET @AS_MSJ  = 'PARA ORDEN DE PAGO EN CHEQUE DEBE INGRESAR LA ENTIDAD FINANCIERA'
		RETURN -1
	END	
	
	IF @AS_TIPO_CUENTA  IS NULL
	BEGIN
		SET @AS_MSJ  = 'PARA ORDEN DE PAGO EN CHEQUE DEBE INGRESAR EL TIPO DE CUENTA'
		RETURN -1
	END	
	
	IF @AS_NUMERO_CUENTA  IS NULL
	BEGIN
		SET @AS_MSJ  = 'PARA ORDEN DE PAGO EN CHEQUE DEBE INGRESAR EL NUMERO DE CUENTA'
		RETURN -1
	END	
END

IF @AS_TIPO_DESEMBOLSO IN( 'OPC','OPE')
BEGIN
	IF NOT EXISTS (SELECT 1 FROM CR_ENTIDAD_FINANCIERA_TIPO_DES WHERE etd_entidad_financiera = @AI_ENTIDAD_FINANCIERA  AND etd_tipo_desemboslo = @AS_TIPO_DESEMBOLSO) 
	BEGIN 
		SET @AS_MSJ  = 'ENTIDAD FINANCIERA NO PERMITIDA PARA ESTE TIPO DE DESEMBOLSO'
		RETURN -1
	END
END

-- VALIDAR NUMERO DE CREDITOS VIGENTES EN PROCESO DE DESEMBOLSO
IF dbo.f_cr_obtener_parametro_b(@LS_PRODUCTO,'BIT_VALIDA_CR_DES') = 1
BEGIN
	EXEC @LI_RET = sp_sl_validacion_nro_creditos @AI_SOLICITUD ,@AS_MSJ OUTPUT,@AI_TIPO OUTPUT
	IF @LI_RET = -1 
		RETURN -1
END

--VALIDACION TASA EFECTIVA
DECLARE 
@LI_TIPO INTEGER

EXEC @LI_RET = sp_sl_validacion_tasa_efectiva_maxima @AI_SOLICITUD ,@AS_MSJ OUTPUT,@LI_TIPO OUTPUT

IF @LI_RET = -1
BEGIN 
	RETURN -1
END


UPDATE SL_SOLICITUD 
SET sol_fecha_1er_pg = @ADT_FECHA_1ER_PG,
sol_fecha_otorgamiento = @ADT_FECHA_DES
WHERE sol_solicitud = @AI_SOLICITUD


EXEC @LI_RET = sp_sl_actualizar_tasa_solicitud @AI_SOLICITUD, @ADEC_TASA

IF @LI_RET = -1 
BEGIN
	SET @AS_MSJ = 'ERROR AL ACTUALIZAR TASA EN LA SOLICITUD'
	RETURN -1
END

IF @AB_RENOVACION = 1
BEGIN
	
	DECLARE @LS_TIPO_DESEMBOLSO CHAR(3), @LS_ESTADO_DESEMBOLSO CHAR(1), @LB_TIPO_DES_MONCERO BIT

	SELECT @LB_TIPO_DES_MONCERO = ISNULL (dbo.f_cr_obtener_parametro_b(@LS_PRODUCTO,'BIT_TIPO_DES_MONCERO'),0)

	
	IF  @LB_TIPO_DES_MONCERO = 1 AND @AS_TIPO_DESEMBOLSO = dbo.f_cr_obtener_parametro_s(@LS_PRODUCTO,'TIPO_DES_MONCERO')
	BEGIN
		SET @LS_TIPO_DESEMBOLSO = @AS_TIPO_DESEMBOLSO 

		SELECT @LS_ESTADO_DESEMBOLSO = est_estado 
		FROM SL_ESTADO
		WHERE est_es_desembolsado = 1
	END
	ELSE
	BEGIN
	
		IF @LB_PERMITE_AUMENTO_CAPITAL = 1  OR @LS_TIPO_OPERACION = 'E' OR @LS_TIPO_OPERACION = 'F'
		BEGIN
			SET @LS_TIPO_DESEMBOLSO = @AS_TIPO_DESEMBOLSO 
			
			SELECT @LS_ESTADO_DESEMBOLSO = est_estado 
			FROM SL_ESTADO
			WHERE est_es_desembolsado = 1

		END
		ELSE 
		BEGIN 
			EXEC @LI_RET =  sp_cr_obtener_tipo_estado_desembolso
			@AS_TIPO_DESEMBOLSO = @LS_TIPO_DESEMBOLSO  OUTPUT,
			@AS_ESTADO_DESEMBOLSO = @LS_ESTADO_DESEMBOLSO OUTPUT
			--IF @LI_RET <> 1 RETURN -1 
		END
	
	END

END
ELSE
	SET @LS_TIPO_DESEMBOLSO = @AS_TIPO_DESEMBOLSO 
/*	
EXEC @LI_RET  = sp_cr_desembolso_insertar
	@AL_SOLICITUD 	= @AI_SOLICITUD,
	@AS_USUARIO 	= @AS_USUARIO,
	@AS_TIPO_DESEMBOLSO = @LS_TIPO_DESEMBOLSO,
	@AS_REFERENCIA 	= @AS_REFERENCIA,
	@AS_FONDO 	= @AS_FONDO,
	@AS_SUBFONDO = @AS_SUBFONDO,
	@ADT_FECHA_DESC = @ADT_FECHA_DES,
	@AI_ENTIDAD_FINANCIERA = @AI_ENTIDAD_FINANCIERA,
	@AS_TIPO_CUENTA = @AS_TIPO_CUENTA,
	@AS_NUMERO_CUENTA = @AS_NUMERO_CUENTA,
	@AS_CREDITO 	= @AS_CREDITO OUT,
	@AM_VALOR_PAGAR = @LM_VALOR OUT,
	@AS_MSJ 	= @AS_MSJ OUTPUT 


IF @LI_RET = -1 
	RETURN -1
*/


EXEC @LI_RET = dbo.sp_cr_insertar_desembolso_detalle
@AI_SOLICITUD = @AI_SOLICITUD,
@AS_USUARIO = @AS_USUARIO,
@AS_TIPO_DESEMBOLSO = @LS_TIPO_DESEMBOLSO,
@AS_REFERENCIA =@AS_REFERENCIA,
@AS_FONDO = @AS_FONDO,
@AS_SUBFONDO = @AS_SUBFONDO,
@ADT_FECHA_DES = @ADT_FECHA_DES,
@AI_ENTIDAD_FINANCIERA = @AI_ENTIDAD_FINANCIERA,
@AS_TIPO_CUENTA = @AS_TIPO_CUENTA,
@AS_NUMERO_CUENTA = @AS_NUMERO_CUENTA,
@AS_XML_DESEMBOLSO = @AS_XML_DESEMBOLSO,
@AS_CREDITO = @AS_CREDITO  OUT,
@AM_VALOR_PAGAR = @LM_VALOR  OUT,
@AS_MSJ = @AS_MSJ  OUT

-- ACTUALIZA EL MONTO A LIQUIDAR SI CREDITO GRUPAL
-- ESTA ACTUALIZACION TAMBIEN SE REALIZA CUANDO SE PROCESA LA APROBACION
-- PERO PUEDEN EXISTIR PRODUCTOS QUE NO REQUIEREN APROBACION.
EXEC @LI_RET = sp_sl_actualizar_monto_liquidar
		@AI_SOLICITUD = @AI_SOLICITUD,
		@AS_USUARIO = @AS_USUARIO,
		@AS_MSJ = @AS_MSJ  OUTPUT


IF @LI_RET = -1  
	RETURN -1 

--INSERT @TIPO_DESEMBOLSO
--	(sec,tipo_desemb ,valor)
--	SELECT des_sec,des_tipo_desembolso, des_monto_liquidar
--	FROM CR_DESEMBOLSO
--	WHERE des_solicitud = @AI_SOLICITUD
--AND 

IF @AB_RENOVACION = 1 
	SET @LM_VALOR_PAGAR = @AM_VALOR_PAGAR 
ELSE
	SET @LM_VALOR_PAGAR = @LM_VALOR 

IF @LB_ES_AHORROS_CASH = 1 OR @LB_ES_AHORROS = 1 
BEGIN
		
	IF @LB_ES_AHORROS_CASH = 1
	BEGIN
	
		IF EXISTS (	SELECT 1
					FROM CL_CLIENTE 
					WHERE (cli_id = @LI_CLIENTE) and 
					(
						(cli_entidad_financiera is null or cli_tipo_cuenta is null or cli_numero_cuenta is null) OR 
						(LTRIM(RTRIM(cli_entidad_financiera)) = '' or LTRIM(RTRIM(cli_tipo_cuenta)) = '' or LTRIM(RTRIM(cli_numero_cuenta)) = '') 
					)
					)
		

		BEGIN
			SET @AS_MSJ = 'REVISE LOS DATOS DE LA CUENTA DEL BANCO DEL CLIENTE'
			RETURN -1
		END

	END 
	
		
	EXEC @LI_RET = sp_cr_desembolso_cuenta_ah 
					@AS_OFICINA = @AS_OFICINA,
					@AS_USUARIO = @AS_USUARIO ,
					@AI_SOLICITUD = @AI_SOLICITUD,
					@AS_CREDITO = @AS_CREDITO, 
					@AS_TIPO_DESEMBOLSO = @AS_TIPO_DESEMBOLSO, 
					@AS_MSJ = @AS_MSJ OUTPUT,
					@AI_TRA_ID = @LI_TRA_ID OUTPUT, 
					@AS_DOCUMENTO = @LS_DOCUMENTO OUTPUT,
					@AI_SEC = 1
		
	IF @LI_RET = -1 
		RETURN -1

	SET @LS_REFERENCIA = CONVERT(VARCHAR(20),@LI_TRA_ID)


	/*
	SELECT @LS_TIPO_TRANS = tds_tipo_trans_ah
	FROM CR_TIPO_DESEMBOLSO
	WHERE tds_tipo_desembolso = 'AH'

	
	EXEC @LI_RET = CUENTAS..sp_ah_insertar_transaccion
		@AS_CUENTA 	= @AS_REFERENCIA,
		@AS_TIPO_TRANS 	= @LS_TIPO_TRANS,
		@AS_OFICINA 	= @AS_OFICINA ,
		@AS_USUARIO	= @AS_USUARIO,
		@AM_VALOR 	= @LM_VALOR_PAGAR,
		@AS_REFERENCIA 	= @AS_CREDITO,
		@AS_REFERENCIA_CTA = NULL,
		@AM_EFECTIVO 	= 0,
		@AM_CHEQUE 	= 0,
		@AS_CONCEPTO 	= NULL,
		@AS_MSJ 	= @AS_MSJ OUTPUT,
		@AI_TRA_ID 	= @LI_TRA_ID OUTPUT
	IF @LI_RET = -1 
		RETURN -1
	*/
	

END 

ELSE
	IF @AS_TIPO_DESEMBOLSO = 'CC'
	BEGIN
		SELECT @LS_TIPO_TRANS = tds_tipo_trans_cc
		FROM CR_TIPO_DESEMBOLSO
		WHERE tds_tipo_desembolso = 'CC'

		EXEC @LI_RET = CUENTAS..sp_cc_insertar_transaccion
		@AS_CUENTA 	= @AS_REFERENCIA,
		@AS_TIPO_TRANS 	= @LS_TIPO_TRANS,
		@AS_OFICINA 	= @AS_OFICINA ,
		@AS_USUARIO 	= @AS_USUARIO,
		@AM_VALOR 	= @LM_VALOR_PAGAR,
		@AS_REFERENCIA 	= @AS_REFERENCIA,
		@AS_REFERENCIA_CTA = NULL,
		@AM_EFECTIVO 	= 0,
		@AM_CHEQUE 	= 0,
		@AS_CONCEPTO 	= NULL,
		@AS_MSJ 	= @AS_MSJ OUTPUT,
		@AI_TRA_ID 	= @LI_TRA_ID OUTPUT

		IF @LI_RET = -1 
			RETURN -1
	END

	ELSE
		IF @AS_TIPO_DESEMBOLSO = 'EF'
		BEGIN
			-- SI NO DESEMBOLSA COMPLETO SOLO ACTUALIZA PARA DESEMBOLSO EN EFECTIVO.... 
			RETURN 1
		END

EXEC @LI_RET = sp_cr_generar_descuentos_ahorros
	@AS_OFICINA = @AS_OFICINA,
	@AS_USUARIO = @AS_USUARIO,
	@AI_SOLICITUD = @AI_SOLICITUD,
	@AS_CREDITO = @AS_CREDITO,
	@AS_MSJ = @AS_MSJ OUTPUT,
	@AI_SEC = 1
 		
IF @LI_RET = -1 
	RETURN -1
	
EXEC @LI_RET = sp_cr_pagar_desembolso 
	@AS_CREDITO 	= @AS_CREDITO, 
	@AS_USUARIO 	= @AS_USUARIO,
	@AS_OFICINA 	= @AS_OFICINA,
	@AM_VALOR	= @LM_VALOR ,
	@AS_MSJ 	= @AS_MSJ OUTPUT,
	@AS_REFERENCIA	= @LS_REFERENCIA,
	@AS_DOCUMENTO   = @LS_DOCUMENTO,
	@AI_SEC			= 1


IF @LI_RET = -1 
	RETURN -1


------------------ PROCESO CASH COLATERAL ----------------------

IF @LB_CASH_COLATERAL = 1 AND @LB_PRECAN_CAP_DES = 1 
BEGIN 

	EXEC @LI_RET = sp_cr_proceso_cash_colateral @AS_USUARIO,@AS_OFICINA,@AI_SOLICITUD,@AS_MSJ OUT 

	IF @LI_RET <> 1
		RETURN -1
END

------------------ PROCESO CASH COLATERAL ----------------------

if @LI_CR_X_INTEGRANTE = 1 
	
	EXEC @LI_RET = sp_cr_generar_cartera_integrante
		@AS_CREDITO 	= @AS_CREDITO,
		@AS_USUARIO 	= @AS_USUARIO,
		@AS_MSJ 	= @AS_MSJ OUT,
		@AI_SEC = 1


else 
	
	EXEC @LI_RET = sp_cr_generar_cartera
		@AS_CREDITO 	= @AS_CREDITO,
		@AS_USUARIO 	= @AS_USUARIO,
		@AS_MSJ 	= @AS_MSJ OUT,
		@AI_SEC		= 1


IF @LI_RET = -1 
	RETURN -1

--  PAGO POR LOS DESCUENTOS QUE SE COBRAN 
--  LOS CUALES SE GENERAN COMO CUOTA CERO PERO UNICAMENTE SI SON RUBROS FINANCIADOS

---------------------------------------------------------------------------

IF EXISTS (SELECT 1 FROM CR_CUOTAS,SL_DESCUENTOS,CR_DESEMBOLSO
		WHERE cuo_credito = @AS_CREDITO AND 
		cuo_credito = CR_DESEMBOLSO.des_credito AND
		CR_DESEMBOLSO.des_solicitud = SL_DESCUENTOS.des_solicitud AND
		CR_DESEMBOLSO.des_sec = 1 AND
		SL_DESCUENTOS.des_rubro_cuota_desembolso = cuo_rubro AND
		SL_DESCUENTOS.des_es_financiado = 1 AND
		cuo_num_cuota = 0 )
BEGIN
	
	SELECT @LM_SALDO_CUOTA_CERO = SUM(cuo_saldo)
	FROM CR_CUOTAS,SL_DESCUENTOS,CR_DESEMBOLSO
	WHERE cuo_credito = @AS_CREDITO AND 
	cuo_credito = CR_DESEMBOLSO.des_credito AND
	CR_DESEMBOLSO.des_solicitud = SL_DESCUENTOS.des_solicitud AND
	CR_DESEMBOLSO.des_sec = 1 AND
	SL_DESCUENTOS.des_rubro_cuota_desembolso = cuo_rubro AND
	SL_DESCUENTOS.des_es_financiado = 1 AND
	cuo_num_cuota = 0 
	
	SET @LM_SALDO_CUOTA_CERO = ISNULL(@LM_SALDO_CUOTA_CERO,0) 
	
	EXEC @LI_RET = sp_cr_tipo_trans_pago_caja 
			@AS_TIPO_TRAN = @LS_TIPO_TRAN OUT
	
	SET @LM_EFECTIVO = @LM_SALDO_CUOTA_CERO
	SET @LM_CHEQUE = 0
	SET @LS_TIPO_TRAN = 'RSE'
	
	IF @LM_SALDO_CUOTA_CERO > 0 
	BEGIN
	
		EXEC @LI_RET =  sp_cr_inserta_transaccion_cr
				@AS_CREDITO = @AS_CREDITO,
				@AS_TIPO_TRANS = @LS_TIPO_TRAN ,
				@AS_MONEDA = @LS_MONEDA ,
				@AM_VALOR = @LM_SALDO_CUOTA_CERO,
				@AM_EFECTIVO = @LM_EFECTIVO,
				@AM_CHEQUE = @LM_CHEQUE,
				@AS_OFICINA = @AS_OFICINA,
				@AS_USUARIO = @AS_USUARIO ,
				@AS_MSJ = @AS_MSJ   OUTPUT,
				@AI_TRAN = @LI_TRAN OUTPUT,
				@AB_ABONO_RECALCULO = 0
	
		IF @LI_RET <> 1 
			RETURN -1 
	
	END
END

---------------------------------------------------------------------------
EXEC @LI_RET = sp_sl_obtener_tasa_mora @AI_SOLICITUD = @AI_SOLICITUD, @AD_TASA_MORA = @LD_TASA_MORA OUTPUT, @AS_MSJ = @AS_MSJ OUTPUT

IF @LI_RET = -1
BEGIN
	SET @AS_MSJ = 'NO SE PUDO OBTENER LA TASA DE MORA, '+ @AS_MSJ
	RETURN -1
END

UPDATE CR_CREDITOS
SET cre_tasa_mora = @LD_TASA_MORA
WHERE cre_credito = @AS_CREDITO

IF ( @@ERROR<> 0 )
BEGIN
	SET @AS_MSJ = 'ERROR AL ACTUALIZAR TASA_MORA DEL CREDITO'
	RETURN -1
END


UPDATE CR_CREDITOS
SET cre_tasa_mora = @LD_TASA_MORA
WHERE cre_credito_grupo = @AS_CREDITO

IF ( @@ERROR<> 0 )
BEGIN
	SET @AS_MSJ = 'ERROR AL ACTUALIZAR TASA_MORA DEL CREDITO GRUPAL'
	RETURN -1
END

---------------------------------------------------------------------------

UPDATE CR_RENOVACION
SET ren_credito_ren =  @AS_CREDITO
WHERE ren_solicitud_ren = @AI_SOLICITUD

IF @@ERROR <> 0 
BEGIN
	SET @AS_MSJ = 'ERROR AL ACTUALIZAR DATOS DE RENOVACION'
	RETURN -1
END

-------------------------------------------------------------------------
--PRI_90

EXEC @LI_RET = sp_cr_insertar_desc_captacion 
@AI_SOLICITUD = @AI_SOLICITUD,
@AS_CREDITO = @AS_CREDITO,
@AS_USUARIO = @AS_USUARIO,
@AS_OFICINA = @AS_OFICINA,
@AB_ES_EXEDENTE = 0, 
@AM_VALOR_EXEDENTE = 0, 
@AM_PLAZO_EXEDENTE = 0, 
@AS_MSJ  = @AS_MSJ OUTPUT

IF @LI_RET = -1 
	RETURN -1


------------	INSERTA PROCESO DE VERIFICACION DE DOCUMENTOS SI ES NECESARIO	--------------------

IF dbo.f_obtener_parametro_b('VERIFICACION_DOC') = 1
BEGIN
	EXEC @LI_RET = sp_cr_insertar_registros_verificacion @AS_CREDITO = @AS_CREDITO, @AS_USUARIO = @AS_USUARIO, @AS_MSJ = @AS_MSJ OUT

	IF @LI_RET <> 1
		RETURN -1
END


------------	CREA CUENTA DE AHORROS PARA RECUPERACION DE AHORRO SI EL PRODUCTO LO DEFINE ASI	--------------------
IF @LB_CREA_CUETA_AH_CR = 1
BEGIN

	SET @LS_CUETA_AH_CR = dbo.f_obtener_parametro_s( 'CR_AH_CUE_TIPO_TRA' )

	if not exists (select 1 from CUENTAS..AH_CUENTAS WHERE cue_cliente = @LI_CLIENTE and cue_tipo = @LS_CUETA_AH_CR)
	BEGIN

		SELECT @LS_NOMBRE = substring(cli_nombre1 + ' ' + cli_apellido1,1,30) 
		FROM CL_CLIENTE
		WHERE cli_id = @LI_CLIENTE


		EXEC @LI_RET = CUENTAS..sp_ah_cuentas_crear 
		@AI_USUARIO = @AS_USUARIO,
		@AS_OFICINA = @AS_OFICINA,
		@AI_CLIENTE = @LI_CLIENTE,
		@AS_ABREVIADO = @LS_NOMBRE,
		@AS_ASESOR = @AS_USUARIO,
		@AS_TIPO_CUENTA = @LS_CUETA_AH_CR,
		@AS_MONEDA = 'D',
		@AS_TIPO_LIBRETA = 'L',
		@AS_CUENTA = @LS_CUENTA OUTPUT,
		@AS_MSJ = @AS_MSJ OUTPUT,
		@AM_AHORRO_ORDINARIO = 0,
		@AM_AHORRO_ESPECIAL = 0,
		@AM_CERTIFICADOS_APORTACION = 0,
		@AM_AHORRO_CESANTIA = 0, 
		@AI_CREA_CERTIFICADO = 0,
		@AI_CREA_CESANTIA = 0,
		@AS_XML_SERVICIOS = NULL,
		@AS_XML_MENOR_EDAD = NULL

		IF @LI_RET <> 1
			RETURN -1
		
	END 


END 

------------	VERIFICA ENCAJE COMPLEMENTARIO CON BASE A DATOS ADICIONALES DE CREDITO	--------------------

IF dbo.f_obtener_parametro_b('CR_ENCJ_COMP') = 1
BEGIN
	EXEC @LI_RET = sp_cr_acreditar_encaje_complementario
									@AI_ID_SOLICITUD = @AI_SOLICITUD, 
									@AS_USUARIO = @AS_USUARIO, 
									@AS_MSJ = @AS_MSJ OUT

	IF @LI_RET <> 1
		RETURN -1
END


RETURN 1
END

