USE CREDITO
GO
/*FECHA		AUTOR	DESCRIPCION
==========	=====	==========================================================
2007-06-08  	BMR 	GENERAR UNA TRANSACCION POR LOS DESCUENTOS DE LA NUEVA OPERACION
2007-06-12  	BMR 	AUMENTAR EL PARAMETRO PARA RENOVACION AUTOMATICA
2009-12-01  	GNF 	CAMBIO POR RETANQUEO
2010-03-10  	DCH 	RETANQUEO MONTO A RECIBIR CERO
2010-03-23  	GNF 	CORRECCION DE LA FECHA DE PRIMER PAGO QUE SE SETEA EN NULL
*/
CREATE   PROCEDURE [dbo].[sp_cr_renovacion_credito]
@AS_USUARIO 	VARCHAR(15),
@AS_OFICINA	CHAR(4),
@AS_MONEDA	CHAR(1),
@AS_CREDITO 	VARCHAR(20),
@AM_VALOR 	MONEY,
@AM_EFECTIVO 	MONEY,
@AM_CHEQUE 	MONEY,
@AI_TRA_ID 	INT OUTPUT,
@AS_MSJ 	VARCHAR(100) OUTPUT,
@AB_RENOVACION_MANUAL BIT = 1,
@AB_RENOVACION_AUTOMATICA BIT = 0,
@AS_TIPO_TRAN CHAR(3) = NULL,
@AS_REFERENCIA VARCHAR(20) = NULL,
@ADT_FECHA_VALOR DATETIME = NULL,
@AI_BANCO_DEP VARCHAR(20) = NULL,
@AS_CUENTA_DEP VARCHAR(20) = NULL,
@AS_TIPO_DESEMBOLSO CHAR(3) = NULL,
@AS_TIPO_CUENTA_DEP CHAR(2) = NULL 
AS

DECLARE @LS_MONEDA CHAR(1), @LS_TIPO_TRAN CHAR(3), @LI_RET INT,
	@LM_GASTOS MONEY, @LM_RENOVACION MONEY, @LM_SALDO MONEY,
	@LM_SALDO_CR MONEY,@LM_MONTO_SOL MONEY,
	@LI_TRAN INT, @LS_CREDITO VARCHAR(20), @LI_SOLICITUD  INT ,
	@LM_A_LIQUIDAR MONEY , @LS_TIPO_DESEMBOLSO CHAR(2),
	@LS_CREDITO_NUEVO VARCHAR(20),
	@LM_SALDO_CUOTA_CERO MONEY,
	@LS_RUBRO_K CHAR(3),
	@LM_VALORES_ANTERIORES MONEY,
	@LM_GASTOS_RENOVACION MONEY,
	@LM_MONTO_RECIBIR MONEY,
	@LS_PRODUCTO VARCHAR (5),
	@LS_TIPO_OPERACION CHAR(1),
	@LI_SOLICITUD_NUEVA INT,
	@LI_RENOVACION INT,
	@LS_FONDO CHAR(3),
	@LS_SUB_FONDO CHAR(3),
	@LB_PERMITE_AUMENTO_CAPITAL BIT,
	@LS_REFERENCIA_AUX VARCHAR(20),
	@LM_VALOR_REFINANCIAR MONEY,
	@LM_VALOR_OTROS MONEY,
	@LM_CUOTAS MONEY,
	@LS_RUBRO CHAR(3),
	@LM_VALOR_PAGO_REFINANCIAMIENTO MONEY,
	@LM_VALOR_CXC_REFINANCIAMIENTO MONEY,
	@LM_VALOR_PAGO_RENOVACION MONEY,
	@LM_VALOR_CXC_RENOVACION MONEY
		

IF NOT EXISTS (	SELECT 1 
				FROM SL_MEDIO_APROB,SL_SOLICITUD,
				CR_RENOVACION
				WHERE 
				CR_RENOVACION.ren_solicitud_ren =  SL_MEDIO_APROB.map_solicitud
				and map_solicitud = sol_solicitud
				and CR_RENOVACION.ren_credito = @AS_CREDITO
				and ren_estado = 'A')
BEGIN
		
	SET @AS_MSJ = 'EL CREDITO NO TIENE APROBADA UNA RENOVACION'
	RETURN -1

END 

SELECT @LI_SOLICITUD_NUEVA = sol_solicitud,
	@LI_RENOVACION = ren_id,
	@LS_FONDO = sol_fondo,
	@LS_SUB_FONDO = sol_subfondo,
	@LS_TIPO_OPERACION = sol_tipo_operacion,
	@LM_MONTO_SOL = sol_monto_solicitado
	FROM SL_MEDIO_APROB,SL_SOLICITUD,
	CR_RENOVACION
	WHERE 
	CR_RENOVACION.ren_solicitud_ren =  SL_MEDIO_APROB.map_solicitud
	and map_solicitud = sol_solicitud
	and CR_RENOVACION.ren_credito = @AS_CREDITO
	and ren_estado = 'A'

		
SELECT @LS_RUBRO_K = rub_rubro FROM CR_RUBROS WHERE rub_es_capital = 1

IF @AB_RENOVACION_MANUAL = 1 AND @AB_RENOVACION_AUTOMATICA = 1
BEGIN
	SET @AS_MSJ = 'NO SE PUEDE REALIZAR UNA RENOVACION AUTOMATICA Y MANUAL A LA VEZ'
	RETURN -1
END 


IF @AB_RENOVACION_MANUAL = 0 AND @AB_RENOVACION_AUTOMATICA = 0
BEGIN
	SET @AS_MSJ = 'NO SE INDICA SI ES UNA RENOVACION AUTOMATICA O MANUAL'
	RETURN -1
END 

------------------------VALIDA SI PERMITE AUMENTO DE CAPITAL ----------------------------------------

	SELECT @LM_SALDO_CR = cre_saldo
	FROM CR_CREDITOS 
	WHERE cre_credito = @AS_CREDITO

	SELECT @LB_PERMITE_AUMENTO_CAPITAL = top_permite_aumento_capital
	FROM CR_TIPO_OPERACION
	WHERE top_tipo_operacion = @LS_TIPO_OPERACION

	SET @LM_SALDO_CR = ISNULL(@LM_SALDO_CR,0)
	SET @LM_MONTO_SOL = ISNULL(@LM_MONTO_SOL,0)
	
	IF (@LM_SALDO_CR  - @LM_MONTO_SOL ) <> 0 AND @LB_PERMITE_AUMENTO_CAPITAL = 0 
	BEGIN
		SET @AS_MSJ = 'ERROR REVISE SALDO DE CREDITO NO ES IGUAL AL DE LA SOLICITUD' 
		RETURN -1
	END 


-----------------------------------------------------------------


IF @AB_RENOVACION_MANUAL = 1 
BEGIN
	SELECT @LM_MONTO_RECIBIR = ren_monto_recibir,
	@LM_A_LIQUIDAR = ren_monto_liquidar
	FROM SL_MEDIO_APROB,
	CR_RENOVACION
	WHERE 
	CR_RENOVACION.ren_solicitud_ren =  SL_MEDIO_APROB.map_solicitud
	and CR_RENOVACION.ren_credito = @AS_CREDITO  
	AND ren_estado = 'A'


	-- UNICAMENTE SE REALIZA LA VALIDACION
	-- SI EXISTE UN VALOR A LIQUIDAR, ES UNICAMENTE CUANDO DEBE PASAR
	-- POR CAJA
	
	IF @LM_A_LIQUIDAR > 0 
	BEGIN
		IF  ABS ( @AM_VALOR - (@AM_EFECTIVO + @AM_CHEQUE ) ) >= 0.01 AND @AS_TIPO_TRAN = dbo.f_obtener_parametro_s ('CRPG') 
		BEGIN
			SET @AS_MSJ = ' A EL VALOR DE LA TRANSACCIÓN DEBE SER IGUAL A LA SUMA DE EFECTIVO Y CHEQUE'
			RETURN -1
		END 
	
		-- VALIDACIÓN DE QUE PROCEDE LA RENOVACIÓN
		EXEC  @LI_RET = sp_cr_valida_pago_renovacion
				@AS_CREDITO = @AS_CREDITO ,
				@AM_PAGO = @AM_VALOR ,
				@AM_MONTO = @LM_RENOVACION OUT,
				@AM_SALDO = @LM_SALDO OUT,
				@AS_MSJ = @AS_MSJ OUT
		
			IF @LI_RET <> 1 RETURN -1 
	END
	
	IF @LM_A_LIQUIDAR = 0 AND @AM_VALOR > 0 
	BEGIN
		SET @AS_MSJ = 'REVISE EL VALOR DE LA TRANSACCIÓN'
		RETURN -1
	END 
	

	
	IF @LM_MONTO_RECIBIR > 0
	BEGIN 
		SELECT @LM_RENOVACION = SL_MEDIO_APROB.map_monto
		FROM SL_MEDIO_APROB,
		CR_RENOVACION
		WHERE 
		CR_RENOVACION.ren_solicitud_ren =  SL_MEDIO_APROB.map_solicitud
		and CR_RENOVACION.ren_credito = @AS_CREDITO
		and ren_estado = 'A'
	
		SET @LM_RENOVACION = ISNULL(@LM_RENOVACION,0) 

		SELECT @LM_SALDO = SUM(cuo_saldo)
		FROM CR_CUOTAS, CR_RUBROS
		WHERE cuo_credito = @AS_CREDITO
		AND cuo_pagada = 0 
		AND rub_rubro = cuo_rubro
		AND cuo_saldo > 0
	
		SET @LM_SALDO = ISNULL(@LM_SALDO,0) 

		-- SI ES RENOVACION CON DESEMBOLSO 
		-- OBTENER LOS VALORES ANTERIORES
		IF @LS_TIPO_OPERACION = 'T'
		BEGIN
			SELECT @LM_VALORES_ANTERIORES = SUM(cuo_saldo)
			FROM CR_CUOTAS, CR_RUBROS
			WHERE cuo_credito = @AS_CREDITO
			AND cuo_pagada = 0 
			AND rub_rubro = cuo_rubro
			AND cuo_rubro != @LS_RUBRO_K 
			AND cuo_saldo > 0
		
		END
		ELSE		
			SELECT @LM_VALORES_ANTERIORES = 0
			
		SET @LM_VALORES_ANTERIORES = ISNULL(@LM_VALORES_ANTERIORES,0)

	END

	/*
	SELECT @LS_PRODUCTO = sol_producto
	FROM CR_RENOVACION, SL_SOLICITUD, CR_CREDITOS
	WHERE cre_credito = @AS_CREDITO 	
	AND ren_estado = 'A'
	AND sol_solicitud = ren_solicitud_ren   
	AND cre_credito = ren_credito


	IF (@LM_MONTO_RECIBIR = 0 AND dbo.f_cr_obtener_parametro_b(@LS_PRODUCTO,'BIT_RETANQUEO')= 1 )
	BEGIN 
		DECLARE @LB_TIPO_DES_MONCERO BIT

		SELECT @LB_TIPO_DES_MONCERO = ISNULL (dbo.f_cr_obtener_parametro_b(@LS_PRODUCTO,'BIT_TIPO_DES_MONCERO'),0)

		IF @LB_TIPO_DES_MONCERO = 1 AND @AS_TIPO_DESEMBOLSO = dbo.f_cr_obtener_parametro_s(@LS_PRODUCTO,'TIPO_DES_MONCERO')
		BEGIN

			SELECT @LM_RENOVACION = SL_MEDIO_APROB.map_monto
			FROM SL_MEDIO_APROB,
			 CR_RENOVACION
			WHERE 
			CR_RENOVACION.ren_solicitud_ren =  SL_MEDIO_APROB.map_solicitud
			and CR_RENOVACION.ren_credito = @AS_CREDITO
		
			SET @LM_RENOVACION = ISNULL(@LM_RENOVACION,0) 
	
			SELECT @LM_SALDO = SUM(cuo_saldo)
			FROM CR_CUOTAS, CR_RUBROS
			WHERE cuo_credito = @AS_CREDITO
			AND cuo_pagada = 0 
			AND rub_rubro = cuo_rubro
			AND cuo_saldo > 0
		
			SET @LM_SALDO = ISNULL(@LM_SALDO,0) 
	
			SELECT @LM_VALORES_ANTERIORES = 0
		END
		ELSE
		BEGIN
			SET @AS_MSJ = 'TIPO DE DESEMBOLSO NO PERMITIDO'
			RETURN -1
		END 

	END
	*/
	IF (@LM_MONTO_RECIBIR = 0 AND ( @LS_TIPO_OPERACION = 'E' OR @LS_TIPO_OPERACION = 'F' OR @LS_TIPO_OPERACION = 'R') )---REESTRUCTURACION
	BEGIN 
	
			
		SELECT @LM_RENOVACION = SL_MEDIO_APROB.map_monto
		FROM SL_MEDIO_APROB,
		 CR_RENOVACION
		WHERE 
		CR_RENOVACION.ren_solicitud_ren =  SL_MEDIO_APROB.map_solicitud
		and CR_RENOVACION.ren_credito = @AS_CREDITO

		SET @LM_RENOVACION = ISNULL(@LM_RENOVACION,0) 

				
		SELECT @LM_SALDO = SUM(cuo_saldo)
		FROM CR_CUOTAS, CR_RUBROS
		WHERE cuo_credito = @AS_CREDITO
		AND cuo_pagada = 0 
		AND rub_rubro = cuo_rubro
		AND cuo_saldo > 0

		SET @LM_SALDO = ISNULL(@LM_SALDO,0) --+ ISNULL(@LM_INTERES_ANTICIPADO,0)

		SELECT @LM_VALORES_ANTERIORES = 0

	END
END

IF @AB_RENOVACION_AUTOMATICA = 1 
BEGIN

	SELECT @LM_SALDO = SUM(cuo_saldo)
	FROM CR_CUOTAS, CR_RUBROS
	WHERE cuo_credito = @AS_CREDITO
	AND cuo_pagada = 0 
	AND rub_rubro = cuo_rubro
	AND cuo_saldo > 0

	SET @LM_SALDO = ISNULL(@LM_SALDO,0) 

	SELECT @LM_VALORES_ANTERIORES = SUM(cuo_saldo)
	FROM CR_CUOTAS, CR_RUBROS
	WHERE cuo_credito = @AS_CREDITO
	AND cuo_pagada = 0 
	AND rub_rubro = cuo_rubro
	AND cuo_rubro <> @LS_RUBRO_K
	AND cuo_saldo > 0

	SET @LM_VALORES_ANTERIORES = ISNULL(@LM_VALORES_ANTERIORES,0)

	SELECT @LM_RENOVACION = SL_MEDIO_APROB.map_monto
	FROM SL_MEDIO_APROB,
		 CR_RENOVACION
	WHERE 
	CR_RENOVACION.ren_solicitud_ren =  SL_MEDIO_APROB.map_solicitud
	and CR_RENOVACION.ren_credito = @AS_CREDITO

	SET @LM_RENOVACION = ISNULL(@LM_RENOVACION,0) 

END

SELECT @LI_SOLICITUD  =  ren_solicitud_ren, 
@LM_A_LIQUIDAR = ren_monto_liquidar 
FROM  CR_RENOVACION
WHERE ren_credito = @AS_CREDITO
AND ren_estado = 'A'

IF @LI_SOLICITUD   IS NULL OR @LI_SOLICITUD  = 0
BEGIN
	SET @AS_MSJ = 'REVISE NO SE ENCUENTRA LA RENOVACION ' + @AS_CREDITO
	RETURN -1 
END

/*
-- 	GASTOS POR RENOVACION ANTES DE QUE SEAN PAGADOS
SELECT @LM_GASTOS = sum(cuo_saldo) 
FROM CR_CUOTAS, CR_RUBROS
WHERE cuo_credito = @AS_CREDITO
and cuo_pagada = 0
and cuo_rubro = rub_rubro
and rub_es_renovacion = 1

IF @@ERROR <> 0
BEGIN
	SET @AS_MSJ = 'PROBLEMAS AL OBTENER LOS GASTOS POR RENOVACION '
	RETURN -1 
END
*/

-- VALIDA VALOR A RENOVARSE Y EL PAGO GENERADO
-- SOLAMENTE SI EL VALOR A LIQUIDAR ES MAYOR A CERO
-- SE GENERA UNA TRANSACCION SOBRE LA OPERACION ANTERIOR
--


IF  @LM_A_LIQUIDAR > 0 AND @AM_VALOR >= 0
BEGIN

	-- PAGO DE CAJA GENERADO PARA PROCESAR LA RENOVACIÓN
	--EXEC sp_cr_tipo_trans_pago_caja @LS_TIPO_TRAN OUT

	EXEC @LI_RET = sp_sl_gastos_renovacion @AS_CREDITO , @LM_GASTOS_RENOVACION OUT, @AS_MSJ OUT, @AI_SIN_FINANCIAMIENTO = 1 
	
	IF @LI_RET < 0  RETURN -1 

	
	IF @LS_TIPO_OPERACION <> 'F'
	BEGIN
		SET @AM_VALOR = @AM_VALOR - @LM_GASTOS_RENOVACION 
	END  
	
	IF @AS_TIPO_TRAN = dbo.f_obtener_parametro_s ('CRPG')
		EXEC sp_cr_tipo_trans_pago_caja @LS_TIPO_TRAN OUT
	ELSE 
		SET @LS_TIPO_TRAN = @AS_TIPO_TRAN
	
	IF  @LS_TIPO_OPERACION = 'F'
	BEGIN
		SET @LM_VALOR_CXC_REFINANCIAMIENTO = 0
		
		SELECT @LM_VALOR_PAGO_REFINANCIAMIENTO = sol_pago_refinanciamiento,
		@LM_VALOR_CXC_REFINANCIAMIENTO = sol_cxc_refinanciamiento
		FROM SL_SOLICITUD
		WHERE sol_solicitud = @LI_SOLICITUD_NUEVA

		SET @LM_VALOR_PAGO_REFINANCIAMIENTO = ISNULL(@LM_VALOR_PAGO_REFINANCIAMIENTO,0)
		SET @LM_VALOR_CXC_REFINANCIAMIENTO = ISNULL(@LM_VALOR_CXC_REFINANCIAMIENTO,0)
		
				
		IF @AM_VALOR <> @LM_VALOR_PAGO_REFINANCIAMIENTO + ISNULL(@LM_GASTOS_RENOVACION,0)
		BEGIN
			SET @AS_MSJ = 'REFINANCIAMIENTO VALOR NO CORRESPONDE CON VALOR DE PAGO INGRESADO EN LA NEGOCIACION' 
			RETURN -1
		END
		
	END	


	IF  @LS_TIPO_OPERACION = 'R' AND isnull(dbo.f_obtener_parametro_b('CR_RENOV_CXC_R'),0) = 1
	BEGIN
		SET @LM_VALOR_CXC_RENOVACION = 0
		
		SELECT @LM_VALOR_PAGO_RENOVACION = sol_pago_renovacion,
		@LM_VALOR_CXC_RENOVACION = sol_cxc_renovacion
		FROM SL_SOLICITUD
		WHERE sol_solicitud = @LI_SOLICITUD_NUEVA
		
		SET @LM_VALOR_PAGO_RENOVACION = ISNULL(@LM_VALOR_PAGO_RENOVACION,0)
		SET @LM_VALOR_CXC_RENOVACION = ISNULL(@LM_VALOR_CXC_RENOVACION,0)
		
		IF @AM_VALOR <> @LM_VALOR_PAGO_RENOVACION + ISNULL(@LM_GASTOS_RENOVACION,0) 
		BEGIN
			SET @AS_MSJ = 'RENOVACION (R) VALOR NO CORRESPONDE CON VALOR DE PAGO INGRESADO EN LA NEGOCIACION' 
			RETURN -1
		END
		
	END	

	/*
	IF  @LS_TIPO_OPERACION = 'T' AND isnull(dbo.f_obtener_parametro_b('CR_RENOV_CXC_T'),0) = 1
	BEGIN
		SET @LM_VALOR_CXC_RENOVACION = 0
		
		SELECT @LM_VALOR_PAGO_RENOVACION = sol_pago_renovacion,
		@LM_VALOR_CXC_RENOVACION = sol_cxc_renovacion
		FROM SL_SOLICITUD
		WHERE sol_solicitud = @LI_SOLICITUD_NUEVA
		
		SET @LM_VALOR_PAGO_RENOVACION = ISNULL(@LM_VALOR_PAGO_RENOVACION,0)
		
		IF @AM_VALOR <> @LM_VALOR_PAGO_RENOVACION 
		BEGIN
			SET @AS_MSJ = 'RENOVACION (T) VALOR NO CORRESPONDE CON VALOR DE PAGO INGRESADO EN LA NEGOCIACION' 
			RETURN -1
		END
		
	END
	*/	

	IF @AM_VALOR > 0 
	BEGIN

		IF @LM_A_LIQUIDAR - @AM_VALOR > 0 AND @LS_TIPO_OPERACION = 'R' AND  isnull(dbo.f_obtener_parametro_b('CR_RENOV_CXC_R'),0) = 1
		BEGIN
		
			SET @LM_VALOR_REFINANCIAR = 0
	
			SET @LM_VALOR_REFINANCIAR = @LM_A_LIQUIDAR - @AM_VALOR - @LM_GASTOS_RENOVACION
	
			SET @LM_VALOR_CXC_RENOVACION = ISNULL(@LM_VALOR_CXC_RENOVACION,0)

			IF @LM_VALOR_REFINANCIAR <> @LM_VALOR_CXC_RENOVACION
			BEGIN
				SET @AS_MSJ = 'VALOR CXC NO CORRESPONDE CON VALOR INGRESADO EN LA NEGOCIACION (R)' 
				RETURN -1
			END
		END 

		/*
		IF @LM_A_LIQUIDAR - @AM_VALOR > 0 AND @LS_TIPO_OPERACION = 'T' AND  isnull(dbo.f_obtener_parametro_b('CR_RENOV_CXC_T'),0) = 1
		BEGIN
		
			SET @LM_VALOR_REFINANCIAR = 0
	
			SET @LM_VALOR_REFINANCIAR = @LM_A_LIQUIDAR - @AM_VALOR - @LM_GASTOS_RENOVACION
	
			SET @LM_VALOR_CXC_RENOVACION = ISNULL(@LM_VALOR_CXC_RENOVACION,0)

			IF @LM_VALOR_REFINANCIAR <> @LM_VALOR_CXC_RENOVACION
			BEGIN
				SET @AS_MSJ = 'VALOR CXC NO CORRESPONDE CON VALOR INGRESADO EN LA NEGOCIACION (T)' 
				RETURN -1
			END
		END
		*/

		SET @LS_REFERENCIA_AUX = SUBSTRING('R.' + @AS_REFERENCIA,1,20) 

		SET @AM_EFECTIVO = @AM_VALOR  

		EXEC @LI_RET =   sp_cr_inserta_transaccion_cr
					@AS_CREDITO = @AS_CREDITO,
					@AS_TIPO_TRANS = @LS_TIPO_TRAN ,
					@AS_MONEDA = @AS_MONEDA ,
					@AM_VALOR = @AM_VALOR ,
					@AM_EFECTIVO = @AM_VALOR ,
					@AM_CHEQUE = 0,
					@AS_OFICINA = @AS_OFICINA,
					@AS_USUARIO = @AS_USUARIO ,
					@AS_MSJ = @AS_MSJ   OUTPUT,
					@AI_TRAN = @AI_TRA_ID  OUTPUT,
					@AB_ABONO_RECALCULO = 0,
					@AS_REFERENCIA = @LS_REFERENCIA_AUX,
					@ADT_FECHA_VALOR = @ADT_FECHA_VALOR,
					@AS_BANCO_DEP = @AI_BANCO_DEP,
					@AS_CUENTA_DEP = @AS_CUENTA_DEP,
					@AB_FORZAR_RECUP_V = 1

		IF @LI_RET = -1
			RETURN -1
			
		EXEC @LI_RET = sp_cr_inserta_renovacion_transaccion @AI_RENOVACION = @LI_RENOVACION,@AI_TRA_ID = @AI_TRA_ID,@AS_MSJ = @AS_MSJ  OUTPUT
		
		IF @LI_RET = -1
			RETURN -1
			
	END
	ELSE
	IF @AM_VALOR < 0 AND @LS_TIPO_OPERACION <> 'F'
	BEGIN
		SET @AS_MSJ = @AS_CREDITO+ ' VALOR LIQUIDAR ' +CONVERT(VARCHAR, @LM_A_LIQUIDAR  )+ ' GASTOS RENOVACION '+CONVERT(VARCHAR, @LM_GASTOS_RENOVACION )+ ' VALOR PAGO '+ CONVERT(VARCHAR, @AM_VALOR)
		RETURN -1
	END	
	
	IF @LM_A_LIQUIDAR - @AM_VALOR > 0 AND @LS_TIPO_OPERACION = 'F' 
	BEGIN
		
		SET @LM_VALOR_REFINANCIAR = 0
	
		SET @LM_VALOR_REFINANCIAR = @LM_A_LIQUIDAR - @AM_VALOR
	
		SET @LS_REFERENCIA_AUX = SUBSTRING('R.' + @AS_REFERENCIA,1,20) 
			
		SET @LM_VALOR_CXC_REFINANCIAMIENTO = ISNULL(@LM_VALOR_CXC_REFINANCIAMIENTO,0)

		IF @LM_VALOR_REFINANCIAR <> @LM_VALOR_CXC_REFINANCIAMIENTO
		BEGIN
			SET @AS_MSJ = 'VALOR CXC NO CORRESPONDE CON VALOR INGRESADO EN LA NEGOCIACION' 
			RETURN -1
		END
	
		SET @LS_TIPO_TRAN = NULL
		
		
		SELECT @LS_TIPO_TRAN = ttr_tipo_tran
		FROM CR_TIPO_TRANSACCION 
		WHERE ttr_es_refinanciamiento = 1 AND 
		ttr_estado = 'A'
		
		

		EXEC @LI_RET =   sp_cr_inserta_transaccion_cr
					@AS_CREDITO = @AS_CREDITO,
					@AS_TIPO_TRANS = @LS_TIPO_TRAN ,
					@AS_MONEDA = @AS_MONEDA ,
					@AM_VALOR = @LM_VALOR_REFINANCIAR,
					@AM_EFECTIVO = 0,
					@AM_CHEQUE = 0,
					@AS_OFICINA = @AS_OFICINA,
					@AS_USUARIO = @AS_USUARIO ,
					@AS_MSJ = @AS_MSJ   OUTPUT,
					@AI_TRAN = @AI_TRA_ID  OUTPUT,
					@AB_ABONO_RECALCULO = 0,
					@AS_REFERENCIA = @LS_REFERENCIA_AUX,
					@ADT_FECHA_VALOR = @ADT_FECHA_VALOR,
					@AS_BANCO_DEP = @AI_BANCO_DEP,
					@AS_CUENTA_DEP = @AS_CUENTA_DEP,
					@AB_FORZAR_RECUP_V = 1 

		IF @LI_RET = -1
			RETURN -1
			
		EXEC @LI_RET = sp_cr_inserta_renovacion_transaccion @AI_RENOVACION = @LI_RENOVACION,@AI_TRA_ID = @AI_TRA_ID,@AS_MSJ = @AS_MSJ  OUTPUT
		
		IF @LI_RET = -1
			RETURN -1
			
		SET @AM_VALOR = @AM_VALOR + @LM_VALOR_REFINANCIAR
	
	END 
		
	
	SET @LM_SALDO = @LM_SALDO - @AM_VALOR 

	SET @AM_VALOR = @LM_GASTOS_RENOVACION 

	IF @AM_VALOR >=0 SET @AM_EFECTIVO = @AM_VALOR  

END




-- IF ABS(@LM_A_LIQUIDAR  - @AM_VALOR ) >= 0.01
-- BEGIN
-- 	SET @AS_MSJ = 'REVISE LOS GASTOS POR RENOVACION'
-- 	RETURN -1 
-- END

--	GENERAR CARTERA
-- SELECT @LS_CREDITO =des_credito  FROM CR_DESEMBOLSO
-- WHERE des_solicitud = @LI_SOLICITUD  

-- NO SE TOMA EN CUENTA
-- SE TOMA EL VALOR A DESEMBOLSAR
--SET @LM_RENOVACION = @LM_RENOVACION - @LM_GASTOS


DECLARE --@LS_CREDITO VARCHAR(20),
--	@LS_MONEDA CHAR(1),
--	@LM_VALOR MONEY,
	@LDT_FECHA_DES DATETIME,
	@LDT_FECHA_1ER_DES DATETIME,
	@LS_OFICINA VARCHAR(4) , 
	@LDEC_TASA DECIMAL ( 18, 4 ),
	@LS_REFERENCIA VARCHAR(20)
--	@LI_RET INT 

-- OJO REVISAR LA TASA

SELECT 
	@LS_CREDITO = ren_credito,
	@LS_MONEDA = sol_moneda,
	@LS_OFICINA = cre_oficina,
	@LDT_FECHA_DES = dbo.FechaSistema(),
	@LDT_FECHA_1ER_DES = sol_fecha_1er_pg,
	@LI_SOLICITUD = ren_solicitud_ren--,
	--@AS_FONDO = case when @AS_FONDO is null then cre_fondo else @AS_FONDO end
FROM CR_RENOVACION, SL_SOLICITUD, CR_CREDITOS
WHERE 
cre_credito = @AS_CREDITO 	
AND ren_estado = 'A'
AND sol_solicitud = ren_solicitud_ren   
AND cre_credito = ren_credito

SELECT @LDEC_TASA  = map_tasa
FROM SL_MEDIO_APROB, SL_SOLICITUD
WHERE map_solicitud = @LI_SOLICITUD
AND map_solicitud = sol_solicitud

SET @LDEC_TASA  = ISNULL(@LDEC_TASA,0)  

IF @LDEC_TASA  <= 0
BEGIN
	SET @AS_MSJ = 'LA TASA NO PUEDE SER MENOR O IGUAL CERO'
	RETURN -1
END

IF @LS_TIPO_OPERACION = 'E'---REESTRUCTURACION
	SELECT @AS_TIPO_DESEMBOLSO = tds_tipo_desembolso FROM CREDITO..CR_TIPO_DESEMBOLSO WHERE tds_es_reestructuracion = 1

IF @LS_TIPO_OPERACION = 'F'---REFINANCIAMIENTO
	SELECT @AS_TIPO_DESEMBOLSO = tds_tipo_desembolso FROM CREDITO..CR_TIPO_DESEMBOLSO WHERE tds_es_refinanciamiento = 1

IF @LS_TIPO_OPERACION = 'R' AND @AS_TIPO_DESEMBOLSO IS NULL  ---RENOVACION
	SELECT @AS_TIPO_DESEMBOLSO = tds_tipo_desembolso FROM CREDITO..CR_TIPO_DESEMBOLSO WHERE tds_es_renovacion = 1


	
	IF (@AS_REFERENCIA IS NULL OR @AS_REFERENCIA =  '')
	BEGIN 
		SET @AS_REFERENCIA = @AS_CUENTA_DEP	
	END

EXEC @LI_RET =  sp_cr_procesar_desembolso
			@AS_USUARIO = @AS_USUARIO ,
			@AS_OFICINA = @AS_OFICINA,
			@AI_SOLICITUD = @LI_SOLICITUD ,
			@AS_TIPO_DESEMBOLSO = @AS_TIPO_DESEMBOLSO,
			@AS_REFERENCIA = @AS_REFERENCIA , 
			@AS_FONDO = @LS_FONDO ,
			@AS_SUBFONDO = @LS_SUB_FONDO,
			@ADT_FECHA_DES = @LDT_FECHA_DES ,
			@ADT_FECHA_1ER_PG = @LDT_FECHA_1ER_DES ,
			@ADEC_TASA = @LDEC_TASA ,
			@AB_RENOVACION = 1, -- PROCESA RENOVACION
			@AM_VALOR_PAGAR  = @AM_VALOR,  -- VALOR DEL PAGO
			@AI_ENTIDAD_FINANCIERA = NULL,
			@AS_TIPO_CUENTA = @AS_TIPO_CUENTA_DEP,
			@AS_NUMERO_CUENTA = @AS_CUENTA_DEP,
			@AS_CREDITO = @LS_CREDITO_NUEVO  OUTPUT,
			@AS_MSJ = @AS_MSJ   OUTPUT

			
	IF @LI_RET <> 1 
		RETURN -1 
		

IF @AS_TIPO_DESEMBOLSO = 'EF'  
BEGIN
	EXEC @LI_RET = sp_cr_desembolso_pago_efectivo 
		@AS_USUARIO = @AS_USUARIO ,
		@AS_OFICINA 	= @AS_OFICINA,
		@AS_MONEDA	= @AS_MONEDA,
		@AS_CREDITO 	= @LS_CREDITO_NUEVO,
		@AM_MONTO 	= @LM_RENOVACION,
		@AS_MSJ 	= @AS_MSJ OUT 

	IF @LI_RET = -1
		RETURN -1
END 



-- EL PAGO DEL SALDO ES MENOR
-- ESTE VALOR NO VA
--SET @LM_SALDO = @LM_SALDO - @AM_VALOR

--  PAGO POR EL CREDITO RENOVADO

IF @AB_RENOVACION_MANUAL = 1
BEGIN
	EXEC @LI_RET = sp_cr_tipo_transaccion_renovacion
		@AS_TIPO_TRAN = @LS_TIPO_TRAN OUT
END

IF @AB_RENOVACION_AUTOMATICA = 1
BEGIN
	EXEC @LI_RET = sp_cr_tipo_transaccion_renovacion_automatica
		@AS_TIPO_TRAN = @LS_TIPO_TRAN OUT
END

SET @AM_EFECTIVO = @LM_SALDO
SET @AM_CHEQUE = 0



--- Ajuste 16/04/2024 RENOVACIONES CRWEB
IF NOT EXISTS (SELECT 1 FROM CR_TIPO_DESEMBOLSO WHERE tds_tipo_desembolso= @AS_TIPO_DESEMBOLSO
AND tds_es_ahorros_cash = 1)

BEGIN

EXEC @LI_RET =   sp_cr_inserta_transaccion_cr
			@AS_CREDITO = @AS_CREDITO,
			@AS_TIPO_TRANS = @LS_TIPO_TRAN ,
			@AS_MONEDA = @AS_MONEDA ,
			@AM_VALOR = @LM_SALDO,
			@AM_EFECTIVO = @AM_EFECTIVO,
			@AM_CHEQUE = @AM_CHEQUE,
			@AS_OFICINA = @AS_OFICINA,
			@AS_USUARIO = @AS_USUARIO ,
			@AS_MSJ = @AS_MSJ   OUTPUT,
			@AI_TRAN = @LI_TRAN OUTPUT,
			@AB_ABONO_RECALCULO = 0


	IF @LI_RET <> 1 
		RETURN -1 
	
	
	EXEC @LI_RET = sp_cr_inserta_renovacion_transaccion @AI_RENOVACION = @LI_RENOVACION,@AI_TRA_ID = @LI_TRAN,@AS_MSJ = @AS_MSJ  OUTPUT
		
	IF @LI_RET = -1
		RETURN -1
	end
/*

EXEC @LI_RET =   sp_cr_inserta_transaccion_cr
			@AS_CREDITO = @AS_CREDITO,
			@AS_TIPO_TRANS = @LS_TIPO_TRAN ,
			@AS_MONEDA = @AS_MONEDA ,
			@AM_VALOR = @LM_SALDO,
			@AM_EFECTIVO = @AM_EFECTIVO,
			@AM_CHEQUE = @AM_CHEQUE,
			@AS_OFICINA = @AS_OFICINA,
			@AS_USUARIO = @AS_USUARIO ,
			@AS_MSJ = @AS_MSJ   OUTPUT,
			@AI_TRAN = @LI_TRAN OUTPUT,
			@AB_ABONO_RECALCULO = 0

	
	IF @LI_RET <> 1 
		RETURN -1 
		
	EXEC @LI_RET = sp_cr_inserta_renovacion_transaccion @AI_RENOVACION = @LI_RENOVACION,@AI_TRA_ID = @LI_TRAN,@AS_MSJ = @AS_MSJ  OUTPUT
		
	IF @LI_RET = -1
		RETURN -1
		*/

-- SE TIENE QUE GENERAR UNA TRANSACCION SOBRE LA NUEVA OPERACION

--  PAGO POR LOS DESCUENTOS QUE SE COBRAN EL LA CAJA
--  LOS CUALES SE GENERAN COMO CUOTA CERO

SELECT @LM_SALDO_CUOTA_CERO = SUM(cuo_saldo)
FROM CR_CUOTAS 
WHERE cuo_credito = @LS_CREDITO_NUEVO AND 
cuo_num_cuota = 0

SET @LM_SALDO_CUOTA_CERO = ISNULL(@LM_SALDO_CUOTA_CERO,0) 

--EXEC @LI_RET = sp_cr_tipo_trans_pago_caja 
--		@AS_TIPO_TRAN = @LS_TIPO_TRAN OUT

SET @AM_EFECTIVO = @LM_SALDO_CUOTA_CERO
SET @AM_CHEQUE = 0



IF @LM_SALDO_CUOTA_CERO > 0 AND @AB_RENOVACION_MANUAL = 1
BEGIN

	IF @LS_TIPO_OPERACION <> 'T'
	
		IF @AS_TIPO_TRAN = dbo.f_obtener_parametro_s ('CRPG')
			EXEC sp_cr_tipo_trans_pago_caja @LS_TIPO_TRAN OUT
		ELSE 
			SET @LS_TIPO_TRAN = @AS_TIPO_TRAN

	
	EXEC @LI_RET =   sp_cr_inserta_transaccion_cr
			@AS_CREDITO = @LS_CREDITO_NUEVO,
			@AS_TIPO_TRANS = @LS_TIPO_TRAN,
			@AS_MONEDA = @AS_MONEDA,
			@AM_VALOR = @LM_SALDO_CUOTA_CERO,
			@AM_EFECTIVO = @AM_EFECTIVO,
			@AM_CHEQUE = @AM_CHEQUE,
			@AS_OFICINA = @AS_OFICINA,
			@AS_USUARIO = @AS_USUARIO ,
			@AS_MSJ = @AS_MSJ   OUTPUT,
			@AI_TRAN = @LI_TRAN OUTPUT,
			@AB_ABONO_RECALCULO = 0,
			@AS_REFERENCIA = @AS_REFERENCIA,
			@ADT_FECHA_VALOR = @ADT_FECHA_VALOR,
			@AS_BANCO_DEP = @AI_BANCO_DEP,
			@AS_CUENTA_DEP = @AS_CUENTA_DEP

	IF @LI_RET <> 1 
		RETURN -1 

	
	EXEC @LI_RET = sp_cr_inserta_renovacion_transaccion @AI_RENOVACION = @LI_RENOVACION,@AI_TRA_ID = @LI_TRAN,@AS_MSJ = @AS_MSJ  OUTPUT
		
	IF @LI_RET = -1
		RETURN -1

END


----DAR DE BAJA GARANTIA CREDITO ANTERIOR SI ES RENOVACION
IF EXISTS (SELECT 1 FROM CR_RENOVACION WHERE ren_solicitud_ren = @LI_SOLICITUD)
BEGIN
	DECLARE @LS_NUM_GAR_ANT VARCHAR (20)
		    
	IF EXISTS(SELECT 1 FROM GR_GARANTIAS_CREDITO,GR_GARANTIAS,GR_CLASE_GARANTIA 
				WHERE grc_credito = @LS_CREDITO
				AND grc_cliente = gar_cliente
				AND grc_sec = gar_sec
				AND cgr_clase_garantia = gar_clase_garantia
				AND cgr_es_pagare = 1)
	BEGIN
		SELECT @LS_NUM_GAR_ANT = gar_num_garantia 
		FROM GR_GARANTIAS_CREDITO, GR_GARANTIAS, GR_CLASE_GARANTIA 
		WHERE grc_credito = @LS_CREDITO
		AND grc_cliente = gar_cliente
		AND grc_sec = gar_sec
		AND cgr_clase_garantia = gar_clase_garantia
	    AND cgr_es_pagare = 1
		
		EXEC  @LI_RET = sp_gr_garantia_baja 
			@AS_NUM_GARANTIA = @LS_NUM_GAR_ANT,
			@AS_USUARIO = @AS_USUARIO,
			@AS_MSJ = @AS_MSJ OUT
			
			IF @LI_RET=-1
			BEGIN
				SET @AS_MSJ = 'ERROR AL DAR DE BAJA GARANTIA' + @AS_MSJ
				RETURN -1
			END
	END	
END	


-- ACTUALIZACION RENOVACION

EXEC @LI_RET = sp_cr_actualizar_renovacion
		@AS_CREDITO = @AS_CREDITO ,
		@AS_CREDITO_REN = @LS_CREDITO_NUEVO ,
		@AS_ESTADO_ACTUAL = 'A',
		@AS_ESTADO = 'P',
		@AB_PAGADO = 1,
		@AS_TIPO_DESEMBOLSO  = NULL,
		@AS_REFERENCIA = NULL,
		@AS_USUARIO = @AS_USUARIO ,
		@AM_VALOR = NULL,
		@AS_MSJ = @AS_MSJ OUTPUT
	
	IF @LI_RET <> 1 
		RETURN -1 
	ELSE 
		SET @AS_MSJ = 'CAMBIOS REGISTRADOS'

RETURN 1



